name: deployment 1
on: push
jobs:
 deployment:
  runs-on: ubuntu-latest
  steps:
  - name: Get the code
    uses: actions/checkout@v4
    with:
      ref: main 
  - name: installing the nodejs 
    uses: actions/setup-node@v4
    with:
      node-version: 18
  - name: accessing the pakage
    run:  cat "04-Practice-Project-(Start)/package.json"
  - name: installing depandencies
    run: npm install --prefix "04-Practice-Project-(Start)"
  - name: lint
    run: npm run lint --prefix "04-Practice-Project-(Start)"
  - name: test the code
    run : npm run test --prefix "04-Practice-Project-(Start)"
  - name: Build code 
    run: npm run build --prefix "04-Practice-Project-(Start)"
 another-jobs-1:
  needs: deployment
  runs-on: ubuntu-latest
  steps:
  - name: Get the code
    uses: actions/checkout@v3
  - name: test another jobs
    run: echo "anohter jobs"
  
